# Site Settings
title: Hello, world! I'm Kashif Rafi
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'  # Use dynamic title for page URLs
baseurl: "/flexible-jekyll" # The subpath of your site, e.g., /blog
url: ""  # Set the base hostname & protocol for your site, e.g., http://example.com
site-twitter: # Optional: Add your Twitter handle if you have one

# Author Settings
author: Kashif Rafi # Your name
author-img: mypics11.jpg # Path to your photo
about-author: I am a Cloud Solution Architect. # Short description about you
social-twitter: # Add your Twitter handle if available
social-facebook: # Add your Facebook handle if available
social-github: artemsheludko # Your GitHub username
social-linkedin: # Add your LinkedIn handle if available
social-email: # Add your email address if you want to make it visible on the site

# Disqus Settings
discus-identifier: mr-brown # Your Disqus identifier (if using Disqus for comments)

# Analytics/Tracking
analytics: # Add Google Analytics ID or any other tracking tool you wish to use

# Build Settings
markdown: kramdown # Markdown parser (kramdown is default and recommended)
plugins:
  - jekyll-sitemap # Generates sitemap.xml
  - jekyll-paginate # Pagination for posts
  - jemoji # Emoji support in posts

# Pagination Settings
paginate: 8 # Number of posts per page
paginate_path: "/page/:num" # URL structure for pagination

# Files/Directories to exclude from the build
exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "yarn.lock"

